{% set name = "capella-console-client" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/capella_console_client-{{ version }}.tar.gz
  sha256: 84f6e953da728525ddc0a3e29294603d6d816295608355480251dfb703ef68af

build:
  entry_points:
    - capella-console-wizard = capella_console_client.cli.wizard:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - httpx >=0.23.0,<0.24.0
    - python >=3.6,<4.0
    - python-dateutil >=2.8.2,<3.0.0
    - retrying >=1.3.3,<2.0.0
    - rich >=12.5.1,<13.0.0
    - typer >=0.6.1,<0.7.0
    - questionary >=1.10.0,<2.0.0
    - tabulate >=0.8.10,<1.0.0
    - geojson >=3.0.1,<4.0.0

test:
  imports:
    - capella_console_client
  commands:
    - pip check
    - capella-console-wizard --help
  requires:
    - pip

about:
  home: https://github.com/capellaspace/console-client
  summary: Python SDK for api.capellaspace.com (search, order, download)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - grmpflh27
    - jordan-heemskerk
